### ISSUE TITLE
Question. Is it possible to change the reCaptcha language dynamically?

### ISSUE THREAD

**Issue by monoflash** [DethAriel/ng-recaptcha#56] opened 2017-09-16 19:07 UTC
Is it possible to change the reCaptcha language dynamically?

Changing the language on the page of the site, I would like to change the language of captcha. Is this possible?

**Comment by DethAriel** [comment] 2017-09-18 19:09
Hello, @monoflash ! This question has already been raised in #25.

Here's the [latest version plunker](https://plnkr.co/edit/mdxhk7uzNqkXoOlHtFfp?p=preview) that has guidance on how this can be achieved.

Note, however, that this is not expected usage pattern for `grecaptcha`, and may result in unforeseen issues (like reverting back to a previous language after some time).

Generally, I would **not** recommend doing this - consider relying on reCAPTCHA language auto-detection and full-page reload in case user decided to change the page language.

**Comment by DethAriel** [comment] 2017-12-26 21:08
Closing since it's a duplicate of #25

**Closed by DethAriel** 2017-12-26 21:08 UTC
