### ISSUE TITLE
Multiple reCAPTCHA components using custom provider error

### ISSUE THREAD

**Issue by mattfirtion** [DethAriel/ng-recaptcha#37] opened 2017-05-12 15:14 UTC
I was able to create the custom provider to load the reCAPTCHA widget and allow for changing of the language.  With two widgets on one page I get an error when loading:

The root looks to be that api.js is loaded multiple times.

```
Uncaught Error: ReCAPTCHA placeholder element must be empty
    at Object.Vp [as render] (recaptcha__en.js:384)
    at RecaptchaComponent.renderRecaptcha (recaptcha.component.js:69)
    at SafeSubscriber._next (recaptcha.component.js:18)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at BehaviorSubject.Subject.next (Subject.js:55)
    at BehaviorSubject.next (BehaviorSubject.js:44)
    at window.ng2recaptchaloaded (locale-recaptcha-provider.ts:39)
```
After submitting and navigating away from the page,
```
ERROR Error: Uncaught (in promise): Error: Invalid ReCAPTCHA client id: 0
Error: Invalid ReCAPTCHA client id: 0
    at Object.Xp [as reset] (recaptcha__en.js:386)
    at recaptcha.component.js:63
    at ZoneDelegate.invoke (zone.js:381)
    at Zone.run (zone.js:141)
    at NgZone.runOutsideAngular (core.es5.js:4019)
    at RecaptchaComponent.grecaptchaReset (recaptcha.component.js:63)
    at RecaptchaComponent.ngOnDestroy (recaptcha.component.js:25)
    at callProviderLifecycles (core.es5.js:11145)
    at callElementProvidersLifecycles (core.es5.js:11114)
    at callLifecycleHooksChildrenFirst (core.es5.js:11098)
    at Object.Xp [as reset] (recaptcha__en.js:386)
    at recaptcha.component.js:63
    at ZoneDelegate.invoke (zone.js:381)
    at Zone.run (zone.js:141)
    at NgZone.runOutsideAngular (core.es5.js:4019)
    at RecaptchaComponent.grecaptchaReset (recaptcha.component.js:63)
    at RecaptchaComponent.ngOnDestroy (recaptcha.component.js:25)
    at callProviderLifecycles (core.es5.js:11145)
    at callElementProvidersLifecycles (core.es5.js:11114)
    at callLifecycleHooksChildrenFirst (core.es5.js:11098)
    at resolvePromise (zone.js:757)
    at resolvePromise (zone.js:728)
    at zone.js:805
    at ZoneDelegate.invokeTask (zone.js:414)
    at Object.onInvokeTask (core.es5.js:4119)
    at ZoneDelegate.invokeTask (zone.js:413)
    at Zone.runTask (zone.js:181)
    at drainMicroTaskQueue (zone.js:574)
    at HTMLFormElement.ZoneTask.invoke (zone.js:480)
```

**Comment by DethAriel** [comment] 2017-05-15 18:26
Hi! Thank you for this issue report. Could you please create a plunker that would show how to reproduce this issue? 

On a side - what is the motivation behind having multiple recaptcha elements on a page?

**Comment by DethAriel** [comment] 2017-05-26 15:49
@mattfirtion could you please re-verify the issue? It could have been resolved by a recaptcha update, as mentioned in https://github.com/DethAriel/ng-recaptcha/issues/38#issuecomment-304294405

**Comment by DethAriel** [comment] 2017-06-12 15:58
Closing due to inactivity

**Closed by DethAriel** 2017-06-12 15:58 UTC
Labels: inactivity closure candidate

**Comment by cassianomon** [comment] 2017-11-21 19:26
Hey @DethAriel I just installed ng-recaptcha and I am having the same issue, I use one `<re-captcha>` for my recover-password component and another for the change-password component.

On my SharedModule I import as:

`
import {
    RecaptchaLoaderService,
    RecaptchaModule,
} from 'ng-recaptcha';
` 
`
imports: [RecaptchaModule],
providers: [RecaptchaLoaderService]
`
The recaptcha shows when navigating, but if I reaload I have the same issue as @mattfirtion.

**Comment by DethAriel** [comment] 2017-11-21 22:55
Hey, @cassianomon ! Thx for your comment! Could you please open a separate issue and follow its template so that I can assist you further? A repro plunker would be great, btw :)
