### ISSUE TITLE
Angular v17 Support

### ISSUE THREAD

**Issue by arman-g** [DethAriel/ng-recaptcha#315] opened 2023-11-23 17:51 UTC
### Summary

I'm submitting a: 

- [ ] bug report
- [ ] feature request
- [x] question / support request 
- [ ] other

### Description

Since Angular v17 is out, are there any planes for **ng-recaptcha** to support it?

**Comment by DethAriel** [comment] 2023-11-23 21:25
duplicate of #310

**Closed by DethAriel** 2023-11-23 21:25 UTC
Labels: duplicate
