### ISSUE TITLE
Invisible captcha bug with badge

### ISSUE THREAD

**Issue by kasperdun** [DethAriel/ng-recaptcha#164] opened 2020-01-09 11:51 UTC
### Summary

I'm submitting a: 
- [x] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

### Description

1. Create 2 modules with re-captcha and routes
2. Open first module page - badge is visible

![image](https://user-images.githubusercontent.com/15229053/72064979-ec8d8100-32fe-11ea-9868-8fa7551ec1f0.png)

3. Go to second module - badge is invisible
![image](https://user-images.githubusercontent.com/15229053/72065004-fca56080-32fe-11ea-9a50-20c2e9e0b6d9.png)

4. Refresh page - badge is visible
![image](https://user-images.githubusercontent.com/15229053/72065142-59088000-32ff-11ea-829a-d3e7a1caa4b2.png)

**Expected result:** 
Both modules has visible badge

https://stackblitz.com/edit/angular-fumgkd

### Demo

- [x] I did my best to come up with a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)

https://stackblitz.com/edit/angular-fumgkd

Lib versions:

* ng-recaptcha: 5.0.0
* Angular: 8.2.0
* Typescript (`tsc --version`): 3.4.5

**Comment by DethAriel** [comment] 2020-09-10 08:28
Hi @kasperdun ! Thank you very much for coming up with a reproducible example!

From what I see, absence of the badge does not prevent recaptcha from functioning properly. Take a look at [this example](https://stackblitz.com/edit/angular-fumgkd-mou53y), which is pretty much the repro you supplied with some `console.log` statements added.

Open the `console` tab in stackblitz and observe its output while you navigate from "Crisis Center" to "Login" -- invisible recaptcha is being executed properly, which is seen by the appropriate log statements.

Now, I understand that the absence of the badge can be perceived as an inconvenience. However, the exact functionality of this badge is not controllable by `ng-recaptcha` library, I'm afraid -- it's part of core recaptcha functionality. Based on publicly available recaptcha API it doesn't appear to be controllable, so I'm afraid I have to close this issue as invalid.

**Closed by DethAriel** 2020-09-10 08:28 UTC

**Comment by UncleBench** [comment] 2023-05-10 15:27
Hi, 

I have run into the exact same problem as @kasperdun. A workaround for the issue described here that fixed the issue for me was to remove the Recaptcha component manually from the DOM upon destroying the component not showing the badge: 
```ts
export class FormWithRecaptchaBadgeComponent implements OnDestroy {
  @ViewChild('captchaRef')
  private readonly reCaptcha: RecaptchaComponent;
  
  ...
  
  ngOnDestroy() {
    this.reCaptcha['elementRef'].nativeElement.remove();
  }
}
```

@DethAriel: Doing some research eventually led me to https://github.com/dozoisch/react-google-recaptcha/pull/196, a pull request in the React ReCaptcha library that apparently fixes similar problems which I suspect to have the same root cause. Once they introduced the call to `grecaptcha.reset()` without a widget ID, the problem went away. As `RecaptchaComponent.grecaptchaReset()` calls reset with the widget ID, I suspect that call to be the culprit and the fix they have found to also apply to this library.

**Comment by DethAriel** [comment] 2023-05-19 02:05
@UncleBench please consider opening a new issue for this. For your issue to have a higher chance of being fixed, please provide a reproduction scenario. Also, if you're feeling brave - contributions are welcome, as long as they follow [the guidelines](https://github.com/DethAriel/ng-recaptcha/blob/master/CONTRIBUTING.md)
