### ISSUE TITLE
Angular 12 / Webpack 5 `process` polyfill issue

### ISSUE THREAD

**Issue by kirillgroshkov** [DethAriel/ng-recaptcha#225] opened 2021-05-14 11:03 UTC
### Summary

I'm submitting a: 

- [x] bug report

### Description

With Angular 12 using Webpack 5, our code now generates this build error:

```
./src/app/pages/pharmacy/pharmacy.page.module.ts:5:0-30 - Error: Module not found: Error: Can't resolve 'process' in '/Users/kirill/Idea/WebSignup/src/app/pages/pharmacy'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "process": require.resolve("process/browser") }'
	- install 'process'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "process": false }

```

It suggests that `ng-recaptcha` is relying on node's `process` module which is not available in the Browser.

So, the solution is to re-evaluate the need for `process` in `ng-captcha` and either remove it, or, provide a polyfill solution (or augment the readme with Angular 12 / Webpack 5 instructions).

**Comment by kirillgroshkov** [comment] 2021-05-14 11:08
Workaround that worked for me is the following. We were using `ngx-build-plus` in our project, which allows to override Webpack configuration. Adding these lines to the configuration "fixed" it:

```js
  resolve: {
    fallback: { "process": false },
  },
```

ps: I haven't tested that actual recaptcha functionality is not broken by that.

**Comment by kirillgroshkov** [comment] 2021-05-14 11:11
UPD: the Workaround above doesn't fix the `ng serve` command (somehow `ng serve` doesn't load our extended webpack config).

**Comment by kirillgroshkov** [comment] 2021-05-14 11:24
UPD: replacing these lines in `angular.json` solved the `ng serve` issue!

```
-          "builder": "@angular-devkit/build-angular:dev-server",
+          "builder": "ngx-build-plus:dev-server",
```

**Comment by DethAriel** [comment] 2021-05-14 20:12
@kirillgroshkov 

> It suggests that ng-recaptcha is relying on node's process module which is not available in the Browser.

What makes you think that? Code that `ng-recaptcha` distributes does not contain any `process` references

**Comment by kirillgroshkov** [comment] 2021-05-15 11:51
> > It suggests that ng-recaptcha is relying on node's process module which is not available in the Browser.
> 
> What makes you think that? Code that `ng-recaptcha` distributes does not contain any `process` references

The error message above clearly states `process`. Also, the workaround above (declaring `process: false`) fixes the error. So, somehow it's `process`-related.

But I also couldn't find any `process` mentions in the `dist` folder of `ng-recaptcha`, which is indeed strange.

**Comment by DethAriel** [comment] 2021-05-15 18:37
ng-recaptcha does not rely on process global variable. Most likely the error you're seeing is coming from somewhere else.

I'm closing this issue since there's nothing to fix at the moment. If you feel like this is an error that indeed related to this library, please provide clear reproduction steps.

**Closed** 2021-05-15 18:37 UTC

**Comment by kirillgroshkov** [comment] 2021-05-15 19:24
Ok, you're right, I just found that the root cause was on the next line in my code:

```typescript
import { RecaptchaV3Module, RECAPTCHA_V3_SITE_KEY } from 'ng-recaptcha'
import { env } from 'process'
```

So, indeed nothing to do with this repo. My bad.
