### ISSUE TITLE
Question: How to us .reset() in component?

### ISSUE THREAD

**Issue by forestweb** [DethAriel/ng-recaptcha#134] opened 2018-12-19 06:20 UTC
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [x] question / support request
- [ ] other

### Description

captchaRef.reset() can be using in template like this:
 `<re-captcha #captchaRef="reCaptcha" (resolved)="resolved($event)" size="invisible"></re-captcha>
<label (click)="captchaRef.reset()"> </label>`

when I click label to action `captchaRef.reset()`.

if I  went to use `captchaRef.reset()` in my component? How can I do?

I try to `@ViewChild`, but it's not work, like this:

`@ViewChild('captchaRef') private captchaRef: any;
this.captchaRef.reset();`

**Comment by dockleryxk** [comment] 2019-01-16 14:51
This is a duplicate of #91

**Comment by DethAriel** [comment] 2019-02-01 21:53
@forestweb the way to do that is exactly through `@ViewChild('captchaRef')`, e.g. like this:

```html
<re-captcha size="invisible" #captchaRef="reCaptcha" (resolved)="response = $event"></re-captcha>
```

```ts
@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent implements AfterViewInit {
  @ViewChild('captchaRef') public captchaRef: RecaptchaComponent;

  public ngAfterViewInit() {
    this.captchaRef.execute();
  }

  public resetCaptcha() {
    this.captchaRef.reset();
  }
}
```

You can find a working example of that [here](https://stackblitz.com/edit/ng-recaptcha-example-lrbafn?file=src%2Fapp%2Fapp.component.html).

**Closed by DethAriel** 2019-02-01 21:53 UTC
