### ISSUE TITLE
ng2-recaptcha is not working in angular 5 as OpaqueToken got deprecated from @angular/core in version 5.

### ISSUE THREAD

**Issue by drakshit** [DethAriel/ng-recaptcha#71] opened 2017-11-08 11:39 UTC
### Summary

I'm submitting a: 
- [ ] bug report
- [ ] feature request
- [ ] question / support request
- [ ] other

**Comment by DethAriel** [comment] 2017-11-08 20:08
Duplicate of #72

**Closed by DethAriel** 2017-11-08 20:08 UTC
