### ISSUE TITLE
Bug: Using ng-recaptcha in different components on the same page navigated by router-outlet

### ISSUE THREAD

**Issue by TamirGit** [DethAriel/ng-recaptcha#38] opened 2017-05-20 23:15 UTC
Hello,

I use router-outlet for navigation of some pages, each of them has a form using your invisible recaptcha.
When I get into one of these pages, and then move to another, I get this exception in my web browser's console:
```
Uncaught TypeError: Cannot read property 'render' of null
    at Vp (recaptcha__en.js:380)
    at Np.Hk (recaptcha__en.js:381)
    at ZoneDelegate.webpackJsonp.606.ZoneDelegate.invokeTask (zone.js:414)
    at Zone.webpackJsonp.606.Zone.runTask (zone.js:181)
    at ZoneTask.invoke (zone.js:476)
    at timer (zone.js:1491)
```
As far as I understand, it happens since the captcha tries to render itself again on the same page, and fails to do that in that previous element since it's not there anymore, because we just routed to a different page. Since there is no bug in recaptcha itself, I assume this issue should be taken care of in your component.

It sounds similar to this #35 issue, however I get a different exception.

Hopefully you can take a look into it and get it fixed and/or suggest me please I can go around it til then.

Thanks in advance!

**Comment by cihy2** [comment] 2017-05-23 13:21
This also happens to me.

**Comment by john-boy** [comment] 2017-05-24 14:53
I have the same error as described by TamirGit.  This creates havoc with router-outlet forms.  Please escalate this issue so we can get a resolution.  After the TypeError is thrown the recaptcha control is not rendered again...forcing the application to reload is the only recourse to restoring normality.

**Comment by Rob-Shnayder** [comment] 2017-05-24 17:26
I am also getting this error. Happening in all environments (most importantly prod). I have the recaptcha on my landing page. It seems that when you complete the recaptcha and route to another page, the recaptcha tries to render itself again. But the element is no longer there, so it throws a 'Cannot read property 'render' of null' error.


Full error:
main.bundle.js:65243 TypeError: Cannot read property 'render' of null
    at Vp (recaptcha__en.js:380)
    at Np.Hk (recaptcha__en.js:381)
    at ZoneDelegate.invokeTask (main.bundle.js:96549)
    at Object.onInvokeTask (main.bundle.js:61485)
    at ZoneDelegate.invokeTask (main.bundle.js:96548)
    at Zone.runTask (main.bundle.js:96449)
    at ZoneTask.invoke (main.bundle.js:96617)

**Comment by john-boy** [comment] 2017-05-24 21:23
I have a suggested workaround.  Move the re-captcha element outside the scope of the router outlet.  I used the application component as the host.  Then you can activate/deactivate using service communication as described in https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#bidirectional-service to coordinate the visibility of the element and transmit the result of the recaptcha operation to the component inside the router outlet.

**Comment by DethAriel** [comment] 2017-05-25 16:15
Guys, thx for submitting this. If I were you I would follow @john-boy suggestion for now. Or feel free to submit a PR with a fix for that

**Comment by TamirGit** [comment] 2017-05-25 16:23
@john-boy I have no idea how to implement your suggestion, can you please share a simple example ? I would really appreciate it.

@DethAriel thank you for your reply, do you think you will be able to fix that in a reasonable time ? (let's say few weeks). In addition, it would be nice to inform this issue in the main page with a suggestion example and explanation of a workaround.

**Comment by DethAriel** [comment] 2017-05-25 17:03
@TamirGit the thing is - reCAPTCHA is not supposed to be present multiple times on a single page, it's just not something is was designed for. I can work on hacking something around that, a couple weeks might be a good estimate for getting this sorted out.

**Comment by Rob-Shnayder** [comment] 2017-05-26 14:19
It seems that this issue has resolved itself due to a new release of recaptcha from google. Version r20170515x was the one causing issues. This morning i checked and it is now version r20170524165316.

**Comment by TamirGit** [comment] 2017-05-26 15:01
Oh my, you're right! that's why in my last attempt to understand the cause of the problem, I moved between only one page containing the captcha and another that doesn't, and nothing appeared in the console. Thank you for updating us, I'm glad it works now and we don't have to work to fix it :)

**Comment by DethAriel** [comment] 2017-05-26 15:48
@Rob-Shnayder that's great news indeed! Thank you for an update

**Comment by DethAriel** [comment] 2017-06-05 15:58
Closing since fixed in reCAPTCHA

**Closed by DethAriel** 2017-06-05 15:58 UTC
Labels: bug, help wanted
