### ISSUE TITLE
Page refresh while navigate page

### ISSUE THREAD

**Issue by smartHasmukh** [DethAriel/ng-recaptcha#84] opened 2018-01-29 06:38 UTC
### Summary
In Angular project When I navigate to reCaptcha page using route then page reload. and When I am removed reCaptcha then navigate to a page that working fine

### Demo

> HTML Code

```
<re-captcha (resolved)="resolved($event)" siteKey="6LcOuyYTAAAAAHTjFuqhA52fmfJ_j5iFk5PsfXaU"></re-captcha>

```

> TYPESCRIPT CODE

```
resolved(captchaResponse: string) {
    console.log(`Resolved captcha with response ${captchaResponse}:`);
}

```
Lib versions:

* ng-recaptcha: 3.0.3
* Angular: 5
* Typescript (`tsc --version`): 1.6.5

**Comment by DethAriel** [comment] 2018-02-14 18:51
@smartHasmukh would you be so kind to provide a reproduction scenario or more details maybe? The code you referenced does not seem to encompass your routing configuration. Also - what is the source of page reload? `ng-recaptcha` does not make page reloads, hence I'm a bit confused

**Comment by DethAriel** [comment] 2018-02-26 17:58
@smartHasmukh were you able to resolve this issue?

**Comment by DethAriel** [comment] 2018-03-07 20:50
Closing this issue for now due to lack of actionable information. @smartHasmukh feel free to add details and reopen if the issue hasn't been resolved yet, or you can share your findings on issue resolution.
Thanks!

**Closed by DethAriel** 2018-03-07 20:50 UTC
Labels: inactivity closure candidate, need info/repro
